### ISSUE TITLE
Syntax highlighting only works for some themes

### ISSUE THREAD

**Issue by Jaeiya** [apple/pkl-vscode#11]
On the theme I'm currently using, which is Dainty Nord, the syntax highlighting doesn't work completely. If I switch to Dark+ I do see the expected highlighting. I assumed maybe it was a problem with my theme, but then I tried the other default theme Dark (visual studio) and it also does not work properly.

This is Dark+
![image](https://github.com/apple/pkl-vscode/assets/2054218/e09a7794-437d-44b9-bf89-207a159664bd)

This is Dark (visual studio)
![image](https://github.com/apple/pkl-vscode/assets/2054218/0b4b6302-a379-47f9-af6a-290b9948492e)'

I then inspected the tokens for each theme and it looks like they're only defined for certain themes, which is odd since I've never seen theme-dependent tokenization before.

Dark (visual studio)
![image](https://github.com/apple/pkl-vscode/assets/2054218/d10a637c-0292-424a-92eb-860c34e80aee)

Dark+
![image](https://github.com/apple/pkl-vscode/assets/2054218/6fc04b74-ef0d-4f37-b561-485d0e9ad96a)

**Comment by stackoverflow** [comment]
This is an issue with the theme, not the grammar. My Typescript files have the same problem on `Dark (visual studio)`.
Some themes use the same colors for different elements or just don't have colors defined for some elements.

**Comment by stackoverflow** [comment]
This seems to be an issue with semantic highlighting support (tree sitter). Our textmate grammar is pretty bare bones at the moment, most of the highlighting is done by tree sitter and it seems some themes don't support it, like `Dark (visual studio)`.
I improved out TextMate grammar but the new version is not released yet. Should come on 0.17 which I hope is a week or two away.

**Comment by Jaeiya** [comment]
Thank you! I appreciate you looking into this. I'll look forward to the upcoming release.

**Comment by stackoverflow** [comment]
@Jaeiya. The new version is released. It should have better syntax highlighting even without tree-sitter.

**Comment by Jaeiya** [comment]
It's definitely better, there's only a couple tokens (that I see immediately) which are still missing accurate scopes:
```pkl
name = species.toUpperCase()
```
The `toUpperCase()` is missing a specific scope, it only has the generic `source.pkl` scope.

```pkl
function greet(bird: Bird): String...
```
The `greet` has the `other.property.pkl` scope, but it should have the same scope as the `toUpperCase()` above, when you create one, since they're both functions.

**Comment by RedCMD** [comment]
technically no
as tree-sitter doesn't have lookbehinds and lookahead doesn't work very well without the C scanner

`toUpperCase()` and `greet()` is very easy to mark as function

**Comment by bioball** [comment]
@Jaeiya Is this still a problem? I just tried out Dainty Nord, and I'm seeing that highlighting is working fine.

<img width="591" alt="Screenshot 2024-10-10 at 4 15 58 PM" src="https://github.com/user-attachments/assets/7ce5792f-9a5b-4e69-9fe1-09c4c37a7130">

**Comment by Jaeiya** [comment]
Well, I tried to check, but for some reason the new version needs Java. When I point it to my Java 23 installation it says it can't get the version information, however when I point it to by Java 21 installation it says it needs java 22 or higher. I literally can't win lol.

I noticed my Java 21 installation is installed as JRE while my Java 23 installation is installed as JDK, is there a difference? They seem to both have the same files and I can manually get the version of both installations through the CLI. Could it be that I need 22 exactly?

**Comment by bioball** [comment]
JRE should be enough.

How are you installing Java? What do you see as the output of `/path/to/jdk23 -version`?

**Comment by bioball** [comment]
We just release pkl-vscode 0.18.1; try upgrading and that should fix your problems!

**Comment by Jaeiya** [comment]
Good news is your `0.18.1` update fixed my Java path issue.

Bad news is I'm having the exact same issue. The exact theme I'm using is: https://marketplace.visualstudio.com/items?itemName=alexanderte.dainty-nord-vscode

That being said, I checked the official Nord theme (which my theme is based on) and it works just fine. I just discovered that the Dainty Nord version I'm using - linked above - is unfortunately now abandoned; the site and repository are now 404'd.

I'm still under the assumption that it should be possible to expose the correct scopes for my theme; however it would be disingenuous of me to ask you to support themes that have either been abandoned or won't receive future updates.

I'll leave it up to you to decide if this is worth supporting.

**Comment by bioball** [comment]
I just tried out both of those themes, and can't reproduce this.

I suspect something weird is going on with your VSCode; maybe another extension is intercepting our tokens somehow.

Maybe try confirming that the file is associated with the Pkl language? Does everything else work, including go-to-definition and such?

**Comment by Jaeiya** [comment]
Well, I cleared out all my settings aside from some keybinds and pointing pkl to the java.exe and still no change.

go-to-definition works as expected, it jumps my cursor to the function definition, so clearly it's active on the file. Like I said, if I install the official Nord theme, it colors the functions and I see the scopes, but using the two themes I mentioned, the scopes are not there...I don't know what could be causing it if you can't reproduce.

Are there any settings you have enabled that I need enabled?

**Comment by Jaeiya** [comment]
Okay, so I figured it out, I need to have `editor.semanticHighlighting.enabled` set to true.

**Comment by bioball** [comment]
TIL that themes can influence whether semantic highlighting works or not. Good find!
