### ISSUE TITLE
[Question] Feature Parity with IntelliJ Plugin planned?

### ISSUE THREAD

**Issue by tsteckenborn** [apple/pkl-vscode#16]
Hey there,

First of all, thank you very much for your efforts!

While reviewing the documentation, I saw that the IntelliJ plugin already supports some useful features, such as code completion, validation, navigation, formatting as well as name, type and constraint checking and type inference.

Are there plans to integrate these into the VSCode plugin as well?

**Comment by stackoverflow** [comment]
Yes. We have a language server on our roadmap which will allow vscode and any other editor that supports a LSP to have all these features.
Can't give you an ETA right now, I'm afraid.

**Comment by SamGalanakis** [comment]
This would be very useful

**Comment by bioball** [comment]
We now have an LSP integration, with many feature implemented. There's still more to go, but, I'm going to close this issue as answered.
