### ISSUE TITLE
Fails under Windows: Spaces in java path break LSP starting

### ISSUE THREAD

**Issue by lucsoft** [apple/pkl-vscode#42]
Most of the time, java gets installed under C:\Program Files. The Plugin fails to resolve the correct java version and defining a java path also fails as it tries to start "C:\Program" and use the path as args.

![image](https://github.com/user-attachments/assets/60da386b-a0a8-4659-ac95-7bdab3f096a5)

Workaround:
Create a symbolic link to user's home folder (assuming there are no spaces in the path) so you can set the java path to something like "C:\Users\mail\javabin\java.exe"

**Comment by bioball** [comment]
This will be fixed by https://github.com/apple/pkl-vscode/pull/41

**Comment by holzensp** [comment]
[0.18.2 is released](https://github.com/apple/pkl-vscode/releases/tag/0.18.2), which ships #41.
