### ISSUE TITLE
Assignment `=` error in `index.pkl`

### ISSUE THREAD

**Issue by RedCMD** [apple/pkl-vscode#7]
The assignment operator `=` is reported as an error `invalid.illegal.pkl` in the file [index.pkl](https://github.com/apple/pkl-vscode/blob/main/src/pkl/index.pkl)
https://github.com/apple/pkl-vscode/blob/c7b00480b7c5d669b6dae630be3974cd72c181e5/src/pkl/index.pkl#L19-L20
![image](https://github.com/apple/pkl-vscode/assets/33529441/d2bb0f57-3a15-4043-b609-3217a389be7f)

**Comment by stackoverflow** [comment]
Our TextMate grammar is pretty bare bones at the moment. I'll take a second look at it soon.

**Comment by RedCMD** [comment]
The TextMate grammar correctly tokenizes it as `keyword.operator.pkl`
it's the semantic highlighting from Tree-sitter that's causing the error

**Comment by stackoverflow** [comment]
Ah yes, I somehow missed that from your image.
You can create an issue on our [tree-sitter repo](https://github.com/apple/tree-sitter-pkl).

**Comment by bioball** [comment]
I believe this is fixed.

<img width="693" alt="Screenshot 2024-10-10 at 4 17 37 PM" src="https://github.com/user-attachments/assets/af2bc6bc-5097-4b48-a9ce-638cf2ddb37e">
